/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectHouseholdRouteImport } from './routes/select-household'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SessionSessionIdRulesRouteImport } from './routes/session.$sessionId.rules'
import { Route as SessionSessionIdReadinessRouteImport } from './routes/session.$sessionId.readiness'
import { Route as SessionSessionIdProfileRouteImport } from './routes/session.$sessionId.profile'
import { Route as SessionSessionIdPacketRouteImport } from './routes/session.$sessionId.packet'
import { Route as SessionSessionIdDocumentsRouteImport } from './routes/session.$sessionId.documents'

const SelectHouseholdRoute = SelectHouseholdRouteImport.update({
  id: '/select-household',
  path: '/select-household',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRulesRoute = SessionSessionIdRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SessionSessionIdRoute,
} as any)
const SessionSessionIdReadinessRoute =
  SessionSessionIdReadinessRouteImport.update({
    id: '/readiness',
    path: '/readiness',
    getParentRoute: () => SessionSessionIdRoute,
  } as any)
const SessionSessionIdProfileRoute = SessionSessionIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SessionSessionIdRoute,
} as any)
const SessionSessionIdPacketRoute = SessionSessionIdPacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => SessionSessionIdRoute,
} as any)
const SessionSessionIdDocumentsRoute =
  SessionSessionIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => SessionSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-household': typeof SelectHouseholdRoute
  '/session/$sessionId': typeof SessionSessionIdRouteWithChildren
  '/session/$sessionId/documents': typeof SessionSessionIdDocumentsRoute
  '/session/$sessionId/packet': typeof SessionSessionIdPacketRoute
  '/session/$sessionId/profile': typeof SessionSessionIdProfileRoute
  '/session/$sessionId/readiness': typeof SessionSessionIdReadinessRoute
  '/session/$sessionId/rules': typeof SessionSessionIdRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-household': typeof SelectHouseholdRoute
  '/session/$sessionId': typeof SessionSessionIdRouteWithChildren
  '/session/$sessionId/documents': typeof SessionSessionIdDocumentsRoute
  '/session/$sessionId/packet': typeof SessionSessionIdPacketRoute
  '/session/$sessionId/profile': typeof SessionSessionIdProfileRoute
  '/session/$sessionId/readiness': typeof SessionSessionIdReadinessRoute
  '/session/$sessionId/rules': typeof SessionSessionIdRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/select-household': typeof SelectHouseholdRoute
  '/session/$sessionId': typeof SessionSessionIdRouteWithChildren
  '/session/$sessionId/documents': typeof SessionSessionIdDocumentsRoute
  '/session/$sessionId/packet': typeof SessionSessionIdPacketRoute
  '/session/$sessionId/profile': typeof SessionSessionIdProfileRoute
  '/session/$sessionId/readiness': typeof SessionSessionIdReadinessRoute
  '/session/$sessionId/rules': typeof SessionSessionIdRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select-household'
    | '/session/$sessionId'
    | '/session/$sessionId/documents'
    | '/session/$sessionId/packet'
    | '/session/$sessionId/profile'
    | '/session/$sessionId/readiness'
    | '/session/$sessionId/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-household'
    | '/session/$sessionId'
    | '/session/$sessionId/documents'
    | '/session/$sessionId/packet'
    | '/session/$sessionId/profile'
    | '/session/$sessionId/readiness'
    | '/session/$sessionId/rules'
  id:
    | '__root__'
    | '/'
    | '/select-household'
    | '/session/$sessionId'
    | '/session/$sessionId/documents'
    | '/session/$sessionId/packet'
    | '/session/$sessionId/profile'
    | '/session/$sessionId/readiness'
    | '/session/$sessionId/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectHouseholdRoute: typeof SelectHouseholdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-household': {
      id: '/select-household'
      path: '/select-household'
      fullPath: '/select-household'
      preLoaderRoute: typeof SelectHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/rules': {
      id: '/session/$sessionId/rules'
      path: '/rules'
      fullPath: '/session/$sessionId/rules'
      preLoaderRoute: typeof SessionSessionIdRulesRouteImport
      parentRoute: typeof SessionSessionIdRoute
    }
    '/session/$sessionId/readiness': {
      id: '/session/$sessionId/readiness'
      path: '/readiness'
      fullPath: '/session/$sessionId/readiness'
      preLoaderRoute: typeof SessionSessionIdReadinessRouteImport
      parentRoute: typeof SessionSessionIdRoute
    }
    '/session/$sessionId/profile': {
      id: '/session/$sessionId/profile'
      path: '/profile'
      fullPath: '/session/$sessionId/profile'
      preLoaderRoute: typeof SessionSessionIdProfileRouteImport
      parentRoute: typeof SessionSessionIdRoute
    }
    '/session/$sessionId/packet': {
      id: '/session/$sessionId/packet'
      path: '/packet'
      fullPath: '/session/$sessionId/packet'
      preLoaderRoute: typeof SessionSessionIdPacketRouteImport
      parentRoute: typeof SessionSessionIdRoute
    }
    '/session/$sessionId/documents': {
      id: '/session/$sessionId/documents'
      path: '/documents'
      fullPath: '/session/$sessionId/documents'
      preLoaderRoute: typeof SessionSessionIdDocumentsRouteImport
      parentRoute: typeof SessionSessionIdRoute
    }
  }
}

interface SessionSessionIdRouteChildren {
  SessionSessionIdDocumentsRoute: typeof SessionSessionIdDocumentsRoute
  SessionSessionIdPacketRoute: typeof SessionSessionIdPacketRoute
  SessionSessionIdProfileRoute: typeof SessionSessionIdProfileRoute
  SessionSessionIdReadinessRoute: typeof SessionSessionIdReadinessRoute
  SessionSessionIdRulesRoute: typeof SessionSessionIdRulesRoute
}

const SessionSessionIdRouteChildren: SessionSessionIdRouteChildren = {
  SessionSessionIdDocumentsRoute: SessionSessionIdDocumentsRoute,
  SessionSessionIdPacketRoute: SessionSessionIdPacketRoute,
  SessionSessionIdProfileRoute: SessionSessionIdProfileRoute,
  SessionSessionIdReadinessRoute: SessionSessionIdReadinessRoute,
  SessionSessionIdRulesRoute: SessionSessionIdRulesRoute,
}

const SessionSessionIdRouteWithChildren =
  SessionSessionIdRoute._addFileChildren(SessionSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectHouseholdRoute: SelectHouseholdRoute,
  SessionSessionIdRoute: SessionSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
